/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student_Inherit;

import Model.Student;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tom
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Vector tbHeader = new Vector();
    Vector tbContent = new Vector();
    DefaultTableModel dtm = new DefaultTableModel(tbContent, tbHeader);
    ProcessStudent ps = new ProcessStudent();

    public NewJFrame() {
        initComponents();
        JCB_ClassID.addItem("61PM1");
        JCB_ClassID.addItem("61PM2");
        tbHeader.add("Mã sinh viên");
        tbHeader.add("Họ tên");
        tbHeader.add("Lớp");
        tbHeader.add("Giới tính");
        tbHeader.add("Điểm");
        tbHeader.add("Xếp loại");
        JTB_Student.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTF_ID = new javax.swing.JTextField();
        JTF_Name = new javax.swing.JTextField();
        JTF_Mark = new javax.swing.JTextField();
        JCB_ClassID = new javax.swing.JComboBox<>();
        JRB_Male = new javax.swing.JRadioButton();
        JRB_Female = new javax.swing.JRadioButton();
        JB_AddStudent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_Student = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sinh viên");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("Họ tên");

        jLabel3.setText("Lớp");
        jLabel3.setToolTipText("");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Điểm");

        JTF_ID.setName(""); // NOI18N
        JTF_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_IDActionPerformed(evt);
            }
        });

        JTF_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_NameActionPerformed(evt);
            }
        });

        JTF_Mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_MarkActionPerformed(evt);
            }
        });

        JRB_Male.setText("Nam");

        JRB_Female.setText("Nữ");

        JB_AddStudent.setText("Thêm");
        JB_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddStudentActionPerformed(evt);
            }
        });

        JTB_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTB_Student);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_AddStudent)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JRB_Male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(JRB_Female))
                    .addComponent(JTF_ID)
                    .addComponent(JTF_Name)
                    .addComponent(JCB_ClassID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTF_Mark))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JCB_ClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JRB_Male)
                    .addComponent(JRB_Female))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTF_Mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_AddStudent)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_IDActionPerformed

    private void JTF_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_NameActionPerformed

    private void JTF_MarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_MarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_MarkActionPerformed

    private void JB_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddStudentActionPerformed
        String ID = JTF_ID.getText();
        String Name = JTF_Name.getText();
        String ClassID = JCB_ClassID.getSelectedItem().toString();
        boolean Gender = true;
        if (JRB_Male.isSelected()) {

            Gender = true;
        }
        if (JRB_Female.isSelected()) {

            Gender = false;
        }
        double mark = Double.parseDouble(JTF_Mark.getText());
        try {
            ps.insertStudent(ID, Name, ClassID, Gender, mark);

        } catch (Exception e) {

        }
        RefeshTable();
    }//GEN-LAST:event_JB_AddStudentActionPerformed
    /**
     * @param args the command line arguments
     */
    public void RefeshTable() {
        dtm.setRowCount(0);
        ArrayList<Student> students = ps.getList();
        for (int i = 0; i < students.size(); i++) {
            Vector tbRow = new Vector();
            tbRow.add(students.get(i).getId());
            System.out.println(students.get(i).getId());
            tbRow.add(students.get(i).getName());
            tbRow.add(students.get(i).getClassID());
            if (students.get(i).isGender()) {
                tbRow.add("Nam");
            } else {
                tbRow.add("Nu");
            }
            tbRow.add(students.get(i).getMark());
            tbRow.add(students.get(i).getRank());
            tbContent.add(tbRow);
        }
        dtm.setDataVector(tbContent, tbHeader);
        JTB_Student.setModel(dtm);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_AddStudent;
    private javax.swing.JComboBox<String> JCB_ClassID;
    private javax.swing.JRadioButton JRB_Female;
    private javax.swing.JRadioButton JRB_Male;
    private javax.swing.JTable JTB_Student;
    private javax.swing.JTextField JTF_ID;
    private javax.swing.JTextField JTF_Mark;
    private javax.swing.JTextField JTF_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
